language: python
python:
    - "3.4"
install:
    - "pip install -r requirements.txt --use-mirrors"
    - "pip install coverage"
    - "pip install coveralls"
script:
    cd brewbox-lib
    py.test
    cd ..
    cd brewbox-agent
    py.test
after_success:
    coveralls
